spring:
  datasource:
    url: jdbc:h2:mem:sttgw;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

logging:
  level:
    root: INFO
    com.ktis.stt_gateway: DEBUG
    org.hibernate.SQL: DEBUG

stt:
  gateway:
    capture:
      interface-name: lo
      dump-path: ./dev-data/DUMP
      dump-enabled: false
    audio:
      output-path: ./dev-data/audio
